-   name: Install php5-fpm
    become: yes
    apt: pkg=php5.6-fpm state=latest
  
  
-   name: Setup php.ini
    become: yes
    lineinfile: dest="/etc/php/5.6/fpm/php.ini"
                regexp="{{ item.reg }}"
                line="{{ item.line }}"
    with_items: php_ini_settings

-   name: Install Apache fcgid
    become: yes
    apt: pkg=libapache2-mod-fcgid state=latest
  
-   name: Enable needed apache mods
    apache2_module: name={{ item }} state=present
    with_items:
        - proxy
        - proxy_fcgi
        - fcgid
    
-   name: Setup fpm config
    lineinfile: dest=/etc/php/5.6/fpm/php-fpm.conf
              create=no
              regexp="{{ item.reg }}"
              line="{{ item.line }}"
    with_items:
        - { reg: 'user = ', line: "user = {{ user }}"}
        - { reg: 'group = ', line: 'group = {{ user }}'}
        - { reg: 'listen = ', line: 'listen = 127.0.0.1:9000' } 
    notify: use FPM