-   name: Add java ppa repo
    become: yes
    apt_repository: repo=ppa:webupd8team/java
    
-   name: auto accept oracle jdk license
    shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    become: yes    

-   name: Install java
    become: yes
    apt: pkg={{ item }} state=latest
    with_items:
      - oracle-java8-installer
      - oracle-java7-installer
      
-   name: Check jackrabbit install
    stat: path=/opt/jackrabbit-standalone-{{ jackrabbit_ver }}.jar
    register: jackrabbit_install
    
-   name: download jackrabbit
    become: yes
    get_url: url=http://www.carfab.com/apachesoftware/jackrabbit/{{ jackrabbit_ver }}/jackrabbit-standalone-{{ jackrabbit_ver }}.jar dest=/opt/jackrabbit-standalone-{{ jackrabbit_ver }}.jar 
    when: jackrabbit_install.stat.exists == False
    
-   name: Add startup script 
    become: yes
    template: src=jack.tpl dest=/opt/jackrabbit.sh
    
-   name: Make jackrabbit jar execuable
    become: yes
    file: path=/opt/jackrabbit-standalone-{{ jackrabbit_ver }}.jar mode=u+rwx

-   name: Make jackrabbit sh execuable
    become: yes
    file: path=/opt/jackrabbit.sh mode=u+rwx
    
-   name: Add to init.d
    become: yes
    ignore_errors: yes
    file: src=/opt/jackrabbit.sh dest=/etc/init.d/jackrabbit state=link force=yes
    
-   name: Start jackrabbit
    service: name=jackrabbit enabled=yes state=restarted
        