-   name: Install php7-fpm
    become: yes
    apt: pkg=php7.0-fpm state=latest
        
-   name: Use FPM
    command: /bin/true
    notify:
        - use FPM
  
-   name: Setup php.ini
    become: yes
    lineinfile: dest="/etc/php/7.0/fpm/php.ini"
                regexp="{{ item.reg }}"
                line="{{ item.line }}"
    with_items: php_ini_settings

-   name: Install Apache fcgid
    become: yes
    apt: pkg=libapache2-mod-fcgid state=latest
  
-   name: Enable needed apache mods
    apache2_module: name={{ item }} state=present
    with_items:
        - proxy
        - proxy_fcgi
        - fcgid
    
-   name: Setup php-fpm config
    when: enviroment == 'dev'
    lineinfile: dest=/etc/php/7.0/fpm/php-fpm.conf
            create=no
            regexp="{{ item.reg }}"
            line="{{ item.line }}"
    with_items:
        - { reg: 'user = ', line: "user = {{ user }}"}
        - { reg: 'group = ', line: 'group = {{ user }}'}
        
-   name: Setup default pool
    when: enviroment == 'dev'
    lineinfile: dest=/etc/php/7.0/fpm/pool.d/www.conf
            create=no
            regexp="{{ item.reg }}"
            line="{{ item.line }}"
    with_items:
        - { reg: 'listen.owner = ', line: 'listen.owner = {{ user }}'}
        - { reg: 'listen.group = ', line: 'listen.group = {{ user }}'}
        - { reg: 'user = ', line: "user = {{ user }}"}
        - { reg: 'group = ', line: 'group = {{ user }}'}

