- name: Install php7-fpm
  sudo: yes
  apt: pkg=php7.0-fpm state=latest
  notify:
      - use FPM
  
  
-   name: Setup php.ini
    sudo: yes
    lineinfile: dest="/etc/php/7.0/fpm/php.ini"
                regexp="{{ item.reg }}"
                line="{{ item.line }}"
    with_items: php_ini_settings

- name: Install Apache fcgid
  sudo: yes
  apt: pkg=libapache2-mod-fcgid state=latest
  
- name: Enable needed apache mods
  apache2_module: name={{ item }} state=present
  with_items:
    - proxy
    - proxy_fcgi
    - fcgid
    
- name: Setup fpm config
  lineinfile: dest=/etc/php/7.0/fpm/php-fpm.conf
            create=no
            regexp="{{ item.reg }}"
            line="{{ item.line }}"
  with_items:
    - { reg: 'user = ', line: "user = {{ user }}"}
    - { reg: 'group = ', line: 'group = {{ user }}'}
    - { reg: 'listen = ', line: 'listen = 127.0.0.1:9000' } 
