-   name: Set dev env for symfony
    lineinfile: dest=/home/vagrant/.bash_profile
                create=yes
                regexp='export SYMFONY_ENV='
                line='export SYMFONY_ENV= {{ enviroment }}'    

-   name: Fix permissions
    command: chmod -R 777 app/logs app/cache
    ignore_errors: yes
    args:
        chdir: /vagrant/
        warn: false
   
-   name: download wkhtmltopdf
    get_url: url=http://hivelocity.dl.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
             dest=/tmp/wkhtmltopdf.deb
   
-   name: install wkhtmltopdf
    apt: deb=/tmp/wkhtmltopdf.deb
    
    
-   name: install composer
    when: enviroment == "prod"
    command: composer install
    args:
        chdir: /vagrant/