-   name: Install PHP Packages
    sudo: yes
    apt: pkg={{ item }} state=latest
    with_items: php_5_packages
  
-   name: Install phpcs
    sudo: yes
    command: pear install PHP_CodeSniffer
    args:
      creates: /usr/bin/phpcs
  
-   name: Install pear channels
    sudo: yes
    command: pear channel-discover {{ item }}
    ignore_errors: yes
    with_items:
         - pear.phpmd.org
         - pear.pdepend.org
         - pear.phpdoc.org

-   name: Install PHP Mess Detector
    sudo: yes
    command: pear install phpmd/PHP_PMD
    args:
        creates: /usr/bin/phpmd
  
-   name: Install PHPDocumentor
    sudo: yes
    command: pear install phpdoc/phpDocumentor
    args:
        creates: /usr/bin/phpdoc
      
-   name: Remove xdebug from CLI
    sudo: yes
    ignore_errors: yes
    command: rm /etc/php5/cli/conf.d/20-xdebug.ini